### ISSUE TITLE
Teamcity support?

### ISSUE THREAD

**Issue by LasseRafn** [mikeerickson/phpunit-pretty-result-printer#11]
I was wondering if Teamcity support is a thing you're considering? PhpStorm / Intellij automatically uses that format and I haven't found a way to disable it.

Would gladly put some work into making a PR myself, but I have no clue how phpunit printers work

**Comment by mikeerickson** [comment]
@LasseRafn Hmmm, I have not used TeamCity either.  I am not really sure what it would take to support it.  I would consider it, depending on the amount of time it would take to add support :-)

**Comment by sgrgrsn** [comment]
Hi @LasseRafn 

I've installed this printer, and I can still run my tests through PhpStorm with (--teamcity) without any issues.

**Comment by LasseRafn** [comment]
Hi @sgrgrsn ! That's odd, mine is just completely empty 🤔 

Will have to try again I guess, maybe I missed something. I just found that running through PhpStorm does not work, but running phpunit directly does.

Sorry for the trouble

**Comment by sgrgrsn** [comment]
Weird.. PhpStorm is running this command when I run my tests:
```
vagrant:///Users/soren/Homestead/usr/bin/php /home/vagrant/Code/my-app/vendor/phpunit/phpunit/phpunit --no-configuration Tests\\Http\\Controllers\\V3\\PostViewControllerTest /home/vagrant/Code/my-app/tests/Http/Controllers/V3/PostViewControllerTest.php --teamcity
```

**Comment by mikeerickson** [comment]
@sgrgrsn @LasseRafn I have tried many different ways to reproduce this (including various operating systems) and in all cases it works as expected?   I am going to close this issue, however, if you are able to find a 100% reproducible step , please reopen a new issue.
