### ISSUE TITLE
Running time for every test

### ISSUE THREAD

**Issue by DanielBadura** [mikeerickson/phpunit-pretty-result-printer#121]
It would be awesome to get some more information for every test that is running. For example the execution time for the test and the test method name or the description. 

I found another pretty printer that does something similar: https://github.com/sempro/phpunit-pretty-print

Maybe we can take this as an inspiration?

**Comment by mikeerickson** [comment]
I will have a look at this project

**Comment by DanielBadura** [comment]
Yes i meant the time for each test that executes. With this the need of the method name (or an description) come with it. Otherwise you cannot determine for which test the execution time is.

**Comment by mikeerickson** [comment]
@DanielBadura I don't see the benefit of adding this support to our project as it would basically been quite similar to what the project in question provides.  If you want to see the verbosity of displaying execution time for each method name, I would think it would be easier just to use that project.
