### ISSUE TITLE
Pretty print assertions

### ISSUE THREAD

**Issue by kanatkubash** [mikeerickson/phpunit-pretty-result-printer#125]
It would be great if assertions were prettified as in mocha:

![image](https://user-images.githubusercontent.com/5927933/46400875-42977000-c71d-11e8-88b2-da412c6e2ff2.png)

**Comment by mikeerickson** [comment]
@kanatkubash I am trying to figure out exactly what you are asking for here?  Using the sample output below (which covers all supported PHPUnit test results), what are you proposing

![image](https://user-images.githubusercontent.com/183153/46425760-6644c100-c6f1-11e8-9242-791165a95b5a.png)

**Comment by kanatkubash** [comment]
Currently it shows assertion error as plain text :
![image](https://user-images.githubusercontent.com/5927933/46437125-6d64e100-c77c-11e8-9f3c-cae013d640fe.png)

I thought it would be readable if expected and actual values are printed in diff way: colored  and on separate lines. Rather than reading assertion output in form of `Failed asserting that %s matches expected %s` Like here:
![image](https://user-images.githubusercontent.com/5927933/46437253-c16fc580-c77c-11e8-9194-8b4f4d1c38f5.png)

**Comment by mikeerickson** [comment]
@kanatkubash OK, now i understand what you are saying.  The current display is default PHPUnit output, but we can override that as well.  I will have a closer look now that i know what you are asking for :-)   Would be nice to make it look even better!

**Comment by mikeerickson** [comment]
@kanatkubash Hey there, I have made some adjustments to reporting, overriding some of the PHPUnit default reports to add some additional color (supports failures, errors, skipped, incomplete and risky tests).  It has been included in the `0.23.0` release
