### ISSUE TITLE
Undefined method ResultPrinter71::formatWithColor()

### ISSUE THREAD

**Issue by andreasschroth** [mikeerickson/phpunit-pretty-result-printer#143]
Not sure if this is related to PHPUnit 8 (didn't use this package before), but I'm getting this error:

```
PHP Fatal error:  Uncaught Error: Call to undefined method Codedungeon\PHPUnitPrettyResultPrinter\ResultPrinter71::formatWithColor() in /vendor/codedungeon/phpunit-result-printer/src/PrinterTrait.php:440
```

**Comment by mikeerickson** [comment]
Yes, it is related to PHPUnit 8.  I will get this fixed as soon as I can (likely Thursday or Friday as I am out of town until thursday)

**Comment by mikeerickson** [comment]
Sorry for the troubles, I have a couple other issues to address related to PHPUnit 8 as well

**Comment by andreasschroth** [comment]
@mikeerickson Alright, thank you for the feedback! No worries, thanks for maintaining the project and I'll check it out once it's PHPUnit 8 compatible.

**Comment by mikeerickson** [comment]
@andreasschroth Hey there, scratched out some time today to have a look at this issue.  I have tagged a new version (0.26.0).  

https://packagist.org/packages/codedungeon/phpunit-result-printer#0.26.0

You can install as 

```bash
composer require --dev codedungeon/phpunit-result-printer "^0.26"
```

**Comment by andreasschroth** [comment]
Thank you, it works! 👍
