### ISSUE TITLE
ExceptionHandler is not instantiable

### ISSUE THREAD

**Issue by solofeed** [mikeerickson/phpunit-pretty-result-printer#147]
PHP: 7.3.1
Laravel: 5.8 fresh installation

 If remove the printer from PHPUnit config, an error is not shown

Stacktrace:
Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable. in /var/www/vendor/laravel/fram
  ework/src/Illuminate/Container/Container.php:962
  Stack trace:
  #0 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(800): Illuminate\Container\Container->notInstantiable('Illuminate\\Cont...')
  #1 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(671): Illuminate\Container\Container->build('Illuminate\\Cont...')
  #2 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(619): Illuminate\Container\Container->resolve('Illuminate\\Cont...', Array)
  #3 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(757): Illuminate\Container\Container->make('Illuminate\\Cont...', Array)
  #4 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(159): Illuminate\Foundation\Application->make('Illuminate\\Cont...')
  #5 /var/www/vendor/laravel

**Comment by mikeerickson** [comment]
What version of php are you using 
What version of PHPUnit are you using 
What version of printer package are you using

**Comment by solofeed** [comment]
@mikeerickson 
php 7.3.1
phpunit 8.0.4
printer 0.26.

**Comment by mikeerickson** [comment]
Thanks, I will have a look and see what’s going on.

**Comment by mikeerickson** [comment]
@solofeed I have tested these exact items and all works fine here?  Would you be willing to post the test app you have so I can try it locally?   Or, you can send it to me via email?   codedungeon@gmail.com

**Comment by mikeerickson** [comment]
Further, is this running the default ExampleTest files, or are you running against your own tests

**Comment by mikeerickson** [comment]
![image](https://user-images.githubusercontent.com/183153/53584404-59a98500-3b38-11e9-8df5-8591618c324b.png)

**Comment by solofeed** [comment]
@mikeerickson I forgot to mention, it was test with the exception, so just fresh laravel 5.8 with PHPUnit 8, and adding throw exception to tested route

**Comment by mikeerickson** [comment]
So, you are testing a route get and throwing an exception in the route index method?

**Comment by solofeed** [comment]
@mikeerickson Exactly

**Comment by mikeerickson** [comment]
@solofeed Again, all is working as expected here.  Would you mind sharing your test and route methods so I can make sure I am testing as you are doing.

**Comment by solofeed** [comment]
@mikeerickson https://github.com/solofeed/laravel/tree/printer-error-proof
 Error reproduces without throwing an exception

`docker run --rm -v $(pwd):/app -w /app php:cli vendor/bin/phpunit` check it

**Comment by mikeerickson** [comment]
OK, I think I have tracked down the issue.  

Edit the `phpunit-printer.yml` and change the following

```
  cd-printer-anybar: false  
```

The default is `true` but this was changed in a previous build (I need to figure out where this has regressed)

**Comment by solofeed** [comment]
Thank you) I will wait for the fix)

**Comment by mikeerickson** [comment]
@solofeed I have tagged a new version `v0.26.1` and it is now available from packagist.  Had you not shared the docker part, I would have still been spinning my wheels as I have been testing locally.

Using the docker part, I was able to see the errors I needed to fix it

![image](https://user-images.githubusercontent.com/183153/53591061-05a69c80-3b48-11e9-97ce-f7d99ecba9eb.png)

**Comment by solofeed** [comment]
@mikeerickson glad to hear that) thank you for the tag) Going to run CI tests with the beautiful printer

**Comment by mikeerickson** [comment]
@solofeed Sorry for the issues.  Glad things are well now.
