### ISSUE TITLE
Setting a custom message for an assertion throws an error

### ISSUE THREAD

**Issue by nesk** [mikeerickson/phpunit-pretty-result-printer#148]
When setting a custom message for an assertion, the printer throws an exception.

Here's an example:

```php
self::assertEquals(1, 2, 'My custom message.');
```

The code fails [at this line](https://github.com/mikeerickson/phpunit-pretty-result-printer/blob/70efe139f174954392582103355a1b4a3d9022e5/src/ResultPrinter71.php#L78) with the following error:

```
sprintf(): Too few arguments
```

This is because the `$exceptionMessage` variable contains two directives instead of one, here's the content of the variable with the example above:

```
"  [01;31m %My custom message.[0m
[01;31m %sFailed asserting that 2 matches expected [01;32m1.[0m[0m
"
```

We have two `%s` directives instead of one, thus the `sprintf()` function fails.

**Comment by mikeerickson** [comment]
@nesk Thank you for the report, I will have a look.  In the meantime, PRs are welcome 👍

**Comment by mikeerickson** [comment]
@nesk I have just tried this agains the current release `0.26.1` and it works as expected?

Here is my test case

```php

<?php

use \PHPUnit\Framework\TestCase;

class CustomAssertMessage extends TestCase
{
    /*
     * @group xxx
     */
    public function test_custom_message()
    {
        $this->assertEquals(1,2,"This is a test message");
    }
}

```

Output appears as expected

![image](https://user-images.githubusercontent.com/183153/53999610-e0da9800-40f8-11e9-93ce-a61bb03292e8.png)

**Comment by nesk** [comment]
Sorry, just tried to reproduce this in a new and dedicated project, but I can't manage to do it.

This issue is probably on me. 😓
