### ISSUE TITLE
Symfony 5?

### ISSUE THREAD

**Issue by gofish543** [mikeerickson/phpunit-pretty-result-printer#154]
Will this package support symfony 5?

**Comment by mikeerickson** [comment]
@gofish543 i will run through a test suite for smyfony 5 and let you know if there are any issues. I plan to have a look over the weekend

**Comment by AlexLisenkov** [comment]
What is the status of this issue?

**Comment by mikeerickson** [comment]
Symfony 5 support is currently in progress.  One of the issues I need to resolve is getting PHPUnit-bridge (https://github.com/symfony/phpunit-bridge) updated to support PHPUnit 9 which I am not finding much information.

**Comment by ddebin** [comment]
`phpunit-bridge` now supports PHPUnit 9.
https://github.com/symfony/phpunit-bridge/releases

**Comment by Arkanius** [comment]
Since now phpunit-bridge supports PHPUnit 9 can we support symfony 5?

**Comment by mikeerickson** [comment]
@Arkanius it is on the task list, but I first must recover from COVID-19 virus.  Hopefully I will be back to work in a couple weeks.  Sorry to holdup your work, but not able to code right now

**Comment by Arkanius** [comment]
Wow, no problem man. Health first! Nice recover!

**Comment by mikeerickson** [comment]
@Arkanius I am finally back to semi-normal and will be reviewing this issue in greater detail soon!

**Comment by Arkanius** [comment]
I'm glad to hear that your fine @mikeerickson ! Thanks!

**Comment by mikeerickson** [comment]
@Arkanius if all goes to plan, I will be working on getting this resolved over the weekend

**Comment by gofish543** [comment]
I believe this issue can be closed?
