### ISSUE TITLE
Phpunit 9.0 compatibility

### ISSUE THREAD

**Issue by lucacri** [mikeerickson/phpunit-pretty-result-printer#156]
Hello,
currently this package works only with phpunit `^8.0`. Can it be raised to `^9.0`?

**Comment by mikeerickson** [comment]
There are currently issues with PHPUnit 9 as some of the internal classes we’ve extended have been marked as internal so we are waiting for PHPUnit response on how we can work with this issue.

**Comment by verschuur** [comment]
In PHPUnit 8 the class was marked as internal, in 9 it has been turned into an interface. 

Myself and a colleague had the same idea for a fix which we implemented for phpunit-pretty-print and seems to fix the issue (albeit at the expanse of backwards compatibility). Check out the pull requests https://github.com/sempro/phpunit-pretty-print/pull/30 and https://github.com/sempro/phpunit-pretty-print/pull/29

**Comment by mikeerickson** [comment]
I have seen this and know what needs to be done to fix it in this project.  Just a matter of time to get it implemented

**Comment by mikeerickson** [comment]
New version 0.27 has been tagged, adding support for PHPUnit 9
