### ISSUE TITLE
Collision Listener fails

### ISSUE THREAD

**Issue by zembrowski** [mikeerickson/phpunit-pretty-result-printer#164]
I’m getting the following exception after activating the Collision Listener as described in the readme.

  `Class "NunoMaduro\Collision\Adapters\Phpunit\Listener" does not exist`

The Listener Class seems to not exist anymore inside Collision Adapters. Is there another way to activate the Collision Listener with pretty-result-printer?

**Comment by mikeerickson** [comment]
That latest version of Collision has removed the listener and cannot be used with printer.  You will need to modify the `phpunit.xml` file and remove the `<listener>` section that was updated when running thrb`init` command. 

we have been in discussion with Nuno about restoring the listener functionality as it added good details to printer output, but as of now, he has not restored the listener functionality.

**Comment by mikeerickson** [comment]
@zembrowski If you want to add you desire to have the listener version restored, here is the ticket submitted to Collision

https://github.com/nunomaduro/collision/issues/102
