### ISSUE TITLE
Width is not calculated correctly on CircleCI (maybe on other CIs too)

### ISSUE THREAD

**Issue by kostaspt** [mikeerickson/phpunit-pretty-result-printer#17]
Maybe there should be an option to print the full line, without looking for the optimal width?

This is a screenshot from CircleCI:
![image](https://user-images.githubusercontent.com/684680/34572969-9175b7ae-f17b-11e7-9da0-2d335648349a.png)

**Comment by mikeerickson** [comment]
@kostaspt What version are you using?  This issue has already been resolved as of `0.5.0` or higher.

**Comment by kostaspt** [comment]
@mikeerickson I'm actually using the `0.5.0` version...

![image](https://user-images.githubusercontent.com/684680/34577274-4665313c-f189-11e7-9f00-9e901d3b6cc7.png)

**Comment by mikeerickson** [comment]
@kostaspt Interesting, we are using with CircleCI internally and all is working as expected.  Let me do some additional debugging on this and will report back.

**Comment by mikeerickson** [comment]
@kostaspt Just a quick update, I have finally been able to reproduce this, however, I don't have an immediate fix.   I will get this worked out over the weekend.

**Comment by mikeerickson** [comment]
Fixed in `0.5.1`
