### ISSUE TITLE
PHP 8 Support ?

### ISSUE THREAD

**Issue by oriceon** [mikeerickson/phpunit-pretty-result-printer#172]

**Comment by mikeerickson** [comment]
@oriceon I just realized that the [0.30.0](https://github.com/mikeerickson/phpunit-pretty-result-printer/releases/tag/0.30.0) branch which provides support for PHP 8 was never actually tagged. I have just corrected this omission and all should be good to go now.

Please let me know if you have other issues

https://github.com/mikeerickson/phpunit-pretty-result-printer/releases/tag/0.30.0
