### ISSUE TITLE
PHP 8.1 compatibility

### ISSUE THREAD

**Issue by oranges13** [mikeerickson/phpunit-pretty-result-printer#183]
**What version of this package are you using?**
0.30.1

**What operating system, Node.js, and npm version?**
Ubuntu Linux (Xenial) / PHP 8.1

**What happened?**
Running unit tests with PHPUnit results in deprecation messages:
```
PHP Deprecated:  Return type of Noodlehaus\AbstractConfig::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
```

**What did you expect to happen?**
Running tests will not display deprecation messages

**Are you willing to submit a pull request to fix this bug?**
I cannot at this time.

However, the solution should be updating the version of `hassankhan/config` in use to the version which supports PHP8.1

**Comment by mikeerickson** [comment]
This issue has been resolved in `0.32.0`
