### ISSUE TITLE
Width is not calculated correctly on GitLab CI

### ISSUE THREAD

**Issue by alexassuncao** [mikeerickson/phpunit-pretty-result-printer#20]
I'm using the 0.5.3 version.

![screenshot from 2018-01-13 17-23-41](https://user-images.githubusercontent.com/30262837/34909359-b2e9c512-f886-11e7-9cb1-f13e6b8cf05c.png)

**Comment by mikeerickson** [comment]
@alexassuncao would you mind sharing tour `./circleci/circl.yml` file. All is fine here so I am curious what differs

**Comment by alexassuncao** [comment]
I don have a circl.yml file, i'm using GitLab. My .gitlab-ci.yml is:

stages:
  - requirements
  - test
  # - pre-deploy
  # - deploy
  # - post-deploy
  - docs

cache:
  key: "$CI_JOB_NAME/$CI_COMMIT_REF_NAME"
  paths:
    - vendor

variables:
  MYSQL_DATABASE: root
  MYSQL_ROOT_PASSWORD: root

composer:pipeline:
  stage: requirements
  image: registry.gitlab.com/sandbox-docker-images/base/composer/7.2:1.1
  script:
    - composer install --prefer-dist --no-ansi -n --no-progress -o --no-suggest
  artifacts:
    name: "${CI_JOB_STAGE}_${CI_COMMIT_SHA}_pipeline"
    paths:
      - ./
  tags:
    - sandbox

composer:production:
  stage: requirements
  image: registry.gitlab.com/sandbox-docker-images/base/composer/7.2:1.1
  script:
    - composer install --prefer-dist --no-ansi -n --no-progress -o --no-suggest --no-dev
  artifacts:
    name: "${CI_JOB_STAGE}_${CI_COMMIT_SHA}_production"
    paths:
      - ./
  only:
    - master
  tags:
    - sandbox

phpunit:
  stage: test
  image: registry.gitlab.com/sandbox-docker-images/base/php7/7.2/fpm:1.2
  services:
    - mysql:5.7
  script:
    - cp .env.example .env
    - php artisan key:generate
    - php artisan config:clear
    - ./vendor/bin/phpunit --configuration phpunit-ci.xml.dist --coverage-text --stderr --colors=never
  dependencies:
    - composer:pipeline
  tags:
    - sandbox

cs-fixer:
  stage: test
  image: registry.gitlab.com/sandbox-docker-images/base/php7/7.2/fpm:1.2
  script:
    - ./vendor/bin/php-cs-fixer fix --verbose --dry-run --config=./.php_cs ./app
  dependencies:
    - composer:pipeline
  tags:
    - sandbox

daux:
  stage: docs
  image: alpine:latest
  script:
    - echo 'it works too!'
  only:
    - master
  when: always
  tags:
    - sandbox
