### ISSUE TITLE
Add TravisCI Support

### ISSUE THREAD

**Issue by mikeerickson** [mikeerickson/phpunit-pretty-result-printer#25]
Consider moving CI tool from CircleCI to TravisCI

**Comment by dbudwin** [comment]
See pull request #29 for implementation.

**Comment by dbudwin** [comment]
It appears my commit to remove CircleCI didn't get merged, was that intentional?

**Comment by mikeerickson** [comment]
Why did you remove circle

**Comment by mikeerickson** [comment]
Yes it was intentional, as I wanted it there.  That is my preferred CI tool, but wanted to make sure it works with Travis as well for personal reasons. 

In the future, please refrain from removing existing code unless it is specifically discussed and confirmed.
