### ISSUE TITLE
Not working with phpunit ~7.0

### ISSUE THREAD

**Issue by godbout** [mikeerickson/phpunit-pretty-result-printer#34]
phpunit ~7.0 enforces return type:

```public function startTest(Test $test): void```

So the printer fails. I can do a PR but I don't think that should be merged into the master branch. Any advice?

**Comment by mikeerickson** [comment]
@godbout this issue was resolved in 0.5.6 (we are now on 0.6.0)

**Comment by godbout** [comment]
😨️
My bad! I seem to have missed something. Thanks @mikeerickson!

**Comment by mikeerickson** [comment]
@godbout no worries 😉

**Comment by godbout** [comment]
Strangely my ```composer update``` doesn't seem to catch up. But the version range seems alright ```"codedungeon/phpunit-result-printer": "^0.4.4",``` it should get updated till 1.0.0, no? or am I too drunk already? 😂️

**Comment by godbout** [comment]
Ok, found out that I was misunderstanding how composer works for **pre-1.0** versions. ```^0.4.4``` means it gets stuck there, while for versions over 1.0 it will go until 2.0. Changed to ```~0.4``` and it's updated now. Thanks! Still learning everyday.

**Comment by mikeerickson** [comment]
I was just about reply stating to use “~0.6” but you already found that 🤓 if you aren’t learning something new every day, you are awake!
