### ISSUE TITLE
Set PHP version requirement to 7.1

### ISSUE THREAD

**Issue by nikolaposa** [mikeerickson/phpunit-pretty-result-printer#53]
PHP version requirement should be set to 7.1, as certain features specific for that version are used in some places. For example, `void` return type is used here: https://github.com/mikeerickson/phpunit-pretty-result-printer/blob/master/src/Printer.php#L160.

**Comment by mikeerickson** [comment]
The project does indeed support PHP 7.0, we take measures to check what version of PHP Is installed and branch code accordingly.

**Comment by nikolaposa** [comment]
It happened to me that Composer installed latest version of this library on a PHP 7.0 machine after I required it (`composer require --dev codedungeon/phpunit-result-printer`) and of course it failed to work due to above mentioned `void` return type. If PHP version requirement was properly set Composer would not allow me to install it on a PHP 7.0 machine.

**Comment by mikeerickson** [comment]
@nikoloaposa can you please confirm which version you have installed.  As of 0.9.x this issue should be resolved.  All is working correctly in my testing?

- PHP Version 
- PHPUnit Version 
- PHPUnit Printer version

**Comment by mikeerickson** [comment]
@nikolaposa Hey there, just tagging you again, seems the above message used wrong handle :-)

**Comment by mikeerickson** [comment]
This has been added to the `0.10.x` release, too much hackiness to support PHP 7.0.x

**Comment by nikolaposa** [comment]
Hi @mikeerickson,

I installed 0.9.3 when I discovered this issue.
