### ISSUE TITLE
Error on Windows: The system cannot find the path specified

### ISSUE THREAD

**Issue by erdmenchen** [mikeerickson/phpunit-pretty-result-printer#56]
On Windows I keep getting the "The system cannot find the path specified." error when running phpunit with the php-pretty-result-printer installed.

Tests run fine but error message is annoying. 

Version information:
Windows 10 (x64) - 1709
phpunit-pretty-result-printer v0.10.1
PHP 7.2.2
PHPUnit 7.0.1

**Comment by erdmenchen** [comment]
The error is printed due to the line         

https://github.com/mikeerickson/phpunit-pretty-result-printer/blob/d70f84e14209db4f2a5e881ee07d7aeb1a6078ee/src/Printer.php#L332

This does not seem to work on Windows...

**Comment by mikeerickson** [comment]
@erdmenchen can you please test against `0.11.0` which was just posted (caught me just before I published new version)

**Comment by erdmenchen** [comment]
I can confirm, now the error message is not shown anymore. 
Thanks a lot!

**Comment by mikeerickson** [comment]
@erdmenchen Awesome, thank you!
