### ISSUE TITLE
Error when composer require codedungeon/phpunit-result-printer@^0.8 --dev

### ISSUE THREAD

**Issue by permadiwibisono** [mikeerickson/phpunit-pretty-result-printer#59]
I got error in my terminal:
[Composer\Downloader\TransportException]                                     
  The "http://packagist.org/p/provider-2018-01%24bf6dfbd24258ae775d775a25568400d088a62534c6c3de33fba60da6776dacf1.json" file could not be downloaded (HT  
  TP/1.1 302 Found)  

I'm using:
- Lumen v5.4
- php v7.0.9
- phpunit v5.7.27

**Comment by mikeerickson** [comment]
How did you attempt to install?

**Comment by mikeerickson** [comment]
Please try just to make certain

`composer require codedungeon/phpunit-result-printer:0.8.2`

When using PHP 7.0.x, you will need to use the compatibility version of `0.8.2` as all newer versions require PHP `7.1`

**Comment by permadiwibisono** [comment]
`v0.8.2` compatible too in PHP `7.1`?

**Comment by mikeerickson** [comment]
No, you will need to use `>= 0.11.0`

**Comment by mikeerickson** [comment]
Moving forward, there is a minimum PHP version of `7.1`

**Comment by permadiwibisono** [comment]
The problem is, I'm using php7.0 in my local development using lampp and my server production using php7.1. So, I cannot using this package. Must re-install my lampp into newer php version. Because there is  no solution to upgrade php only in lampp.

**Comment by mikeerickson** [comment]
@permadiwibisono Good news... I just tested `0.8.2` with `PHPUnit 5.7.27` and `PHP v7.1.3` and all is working just fine.

**Comment by mikeerickson** [comment]
```
    "require": {
        "php": "^7.1.3"
    },
    "require-dev": {
        "codedungeon/phpunit-result-printer": "0.8.2",
        "phpunit/phpunit": "^5.7"
    },
```
