### ISSUE TITLE
Library not compatible with PHPUnit 7.1.1

### ISSUE THREAD

**Issue by tarlepp** [mikeerickson/phpunit-pretty-result-printer#63]
I noticed that library isn't currently compatible with PHPUnit 7.1 

```
Declaration of Codedungeon\PHPUnitPrettyResultPrinter\_ResultPrinter::writeProgress($progress): void should be compatible with PHPUnit\TextUI\ResultPrinter::writeProgress(string $progress): void
```

**Comment by mikeerickson** [comment]
what version do you have installed.  The current version is definitely compatible with PHPUnit 7.1

**Comment by mikeerickson** [comment]
versions `0.11.2` and greater is working with PHPUnit 7.1 (I just ran compatibility testing

**Comment by tarlepp** [comment]
@mikeerickson If I update to `"phpunit/phpunit": "7.1.1"` I'm getting that error:

```
wunder@code-2017-VirtualBox:~/PhpstormProjects/symfony-flex-backend2$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Updating phpunit/phpunit (7.0.3 => 7.1.1): Loading from cache
Writing lock file
Generating autoload files
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class

What about running composer global require symfony/thanks && composer thanks now?
This will spread some 💖  by sending a ★  to the GitHub repositories of your fellow package maintainers.

Executing script cache:clear --no-warmup [OK]
Executing script cache:warmup [OK]
Executing script assets:install --symlink --relative public [OK]
Executing script requirements-checker [OK]
Executing script security-checker security:check --end-point=http://security.sensiolabs.org/check_lock [OK]

> Companienv\Composer\ScriptHandler::run
wunder@code-2017-VirtualBox:~/PhpstormProjects/symfony-flex-backend2$ ./vendor/bin/phpunit 

In Printer.php line 24:
                                                                                                                                                             
  Declaration of Codedungeon\PHPUnitPrettyResultPrinter\_ResultPrinter::writeProgress($progress): void should be compatible with PHPUnit\TextUI\ResultPrint  
  er::writeProgress(string $progress): void                                                                                                                  
                                                                                                                                                             

wunder@code-2017-VirtualBox:~/PhpstormProjects/symfony-flex-backend2$ 
```

**Comment by mikeerickson** [comment]
Ah, wait my error here.  You clearly stated PHPUnit 7.1 (I kept reading and referencing PHP 7.1). I have only verified against PHPunit 7.0.3. 

I will test against all available versions of PHPUnit shortly.

**Comment by mikeerickson** [comment]
Can you please test the `0.12.0` version I just posted.

**Comment by tarlepp** [comment]
@mikeerickson nope, still getting:

```
wunder@code-2017-VirtualBox:~/PhpstormProjects/symfony-flex-backend2$ ./vendor/bin/phpunit 

In Printer.php line 328:
                                                                                                                         
  Declaration of Codedungeon\PHPUnitPrettyResultPrinter\Printer::writeProgress($progress): void should be compatible wi  
  th PHPUnit\TextUI\ResultPrinter::writeProgress(string $progress): void                                                 
```

See the PHPUnit source: https://github.com/sebastianbergmann/phpunit/blob/master/src%2FTextUI%2FResultPrinter.php#L489 and compare that to your https://github.com/mikeerickson/phpunit-pretty-result-printer/blob/master/src/Printer.php#L132

**Comment by tarlepp** [comment]
Also same error will occur with `protected function writeProgressWithColor($color, $buffer): void` which should be `protected function writeProgressWithColor(string $color, string $buffer): void`

And maybe some another methods may have similar methods.

**Comment by tarlepp** [comment]
Also you can see those warnings (errors on my case - because I use `declare(strict_types = 1);`) on your TravisCI https://travis-ci.org/mikeerickson/phpunit-pretty-result-printer/jobs/363210307

**Comment by mikeerickson** [comment]
Yes, I am seeing these now, I committed a "bad" version, working on fixing this issue now.  Got messed up with some merge conflicts and selected the "wrong" code.

**Comment by mikeerickson** [comment]
@tarlepp OK, all should be cleared now, version `0.12.1` posted and tested clean locally.  My apologies for the confusion

**Comment by tarlepp** [comment]
@mikeerickson yeah seems to work like a charm with `0.12.1` - and thanks for quick response about this issue.

**Comment by mikeerickson** [comment]
@tarlepp No worries, glad I was able to turn it around quickly.  I just happened to be working on some other OSS stuff so I was able to jump on this one.   Thank you for the report :-)
