### ISSUE TITLE
Alignments of test marks on first line if/when there is "couple" of tests

### ISSUE THREAD

**Issue by tarlepp** [mikeerickson/phpunit-pretty-result-printer#67]
Picture below should show this problem
![image](https://user-images.githubusercontent.com/595561/38436511-73e2a044-39dd-11e8-8a52-df7ccd1663bb.png)

**Comment by mikeerickson** [comment]
@tarlepp I have just posted `0.12.2` to address this issue.  The CUT should be printed for each, but had a regression error

**Comment by mikeerickson** [comment]
I should appear as 

![image](https://user-images.githubusercontent.com/183153/38448882-1f330162-39bd-11e8-89c9-469382dc2f64.png)

**Comment by tarlepp** [comment]
@mikeerickson yeah that `0.12.2` seems to fix that - thanks once again!
