### ISSUE TITLE
Ambiguous class resolution

### ISSUE THREAD

**Issue by tobz-nz** [mikeerickson/phpunit-pretty-result-printer#74]
I'm getting this warning when installing/updating composer:

Is there a way to fix this?

php 7.2.4 (brew)
Laravel 5.6 (phpunit ~7.0)

```
Warning: Ambiguous class resolution, "Codedungeon\PHPUnitPrettyResultPrinter\_ResultPrinter" was found in both "/Users/tobyevans/Code/dovetailx/api.dovetailx/vendor/codedungeon/phpunit-result-printer/src/ResultPrinter5.php" and "/Users/tobyevans/Code/dovetailx/api.dovetailx/vendor/codedungeon/phpunit-result-printer/src/ResultPrinter6.php", the first will be used.
Warning: Ambiguous class resolution, "Codedungeon\PHPUnitPrettyResultPrinter\_ResultPrinter" was found in both "/Users/tobyevans/Code/dovetailx/api.dovetailx/vendor/codedungeon/phpunit-result-printer/src/ResultPrinter5.php" and "/Users/tobyevans/Code/dovetailx/api.dovetailx/vendor/codedungeon/phpunit-result-printer/src/ResultPrinter70.php", the first will be used.
Warning: Ambiguous class resolution, "Codedungeon\PHPUnitPrettyResultPrinter\_ResultPrinter" was found in both "/Users/tobyevans/Code/dovetailx/api.dovetailx/vendor/codedungeon/phpunit-result-printer/src/ResultPrinter5.php" and "/Users/tobyevans/Code/dovetailx/api.dovetailx/vendor/codedungeon/phpunit-result-printer/src/ResultPrinter71.php", the first will be used.
```

**Comment by mikeerickson** [comment]
The warnings are harmless.  I have to maintain 4 separate Result Printers based on the version of PHPUnit that is being used (5, 6, 7.0 and 7.1). This error is prompted because of the 4 different classes with same name being exported as _ResultPrinter (all with different signatures) which then extend PHPUnit ResultPrinter class.

Mike Erickson
codedungeon@gmail.com

**Comment by tobz-nz** [comment]
I know warning are harmless, except for looking terrible and unprofessional in my opinion.
Wouldn't it make more sense to just name the classes separately and let eh user load the correct one for their setup?

Or load the correct class in the version check - instead of defining the class.

I'm just saying it shouldn't be too difficult to not have the warnings.

**Comment by mikeerickson** [comment]
I Have a few different ideas of how l want to handle this, I just need to pick the approach that Is maintainable.

**Comment by mikeerickson** [comment]
Like all things related to OSS allocating the time is minor hurdle.  I try to be all things to all people, but that sometimes not easy. I will get it addressed as soon as possible.

**Comment by assertchris** [comment]
Fixed in https://github.com/mikeerickson/phpunit-pretty-result-printer/pull/75
