### ISSUE TITLE
Compatibility with PHP Unit 7 ResultsPrinter interface

### ISSUE THREAD

**Issue by jasonsaayman** [mikeerickson/phpunit-pretty-result-printer#81]
Hi

It seems that the Printer.php file is not compatible with the  _ResultsPrinter interface in PHP unit 7.

Two functions are affected, that being `writeProgress` and `writeProgressWithColor`.

**writeProgress changes**
_From:_
` ...
protected function writeProgress($progress)
...`
_To:_
`...
protected function writeProgress(string $progress): void
...`

**writeProgressWithColor changes**
_From:_
` ...
protected function writeProgressWithColor($color, $buffer)
...`
_To:_
`...
protected function writeProgressWithColor($color, $buffer): void
...`

Thanks

**Comment by jasonsaayman** [comment]
Hi Mike

Sorry I realized after creating this issue that I was on an older version. Upgrading to the newest version fixed this issue.

Thank you

**Comment by mikeerickson** [comment]
Awesome, happy to hear.  We’ve spent quite a bit of time over last few weeks ironing out all these types of issues, very confident we have addressed them all, thus reason for asking
