### ISSUE TITLE
Class 'PHPUnit\Runner\Version' not found in codedungeon/phpunit-result-printer/src/Printer.php on line 15

### ISSUE THREAD

**Issue by regiszanandrea** [mikeerickson/phpunit-pretty-result-printer#84]
Hi,

I got this error when I tried to run phpunit with the package:

`Uncaught Error: Class 'PHPUnit\Runner\Version' not found in codedungeon/phpunit-result-printer/src/Printer.php on line 15`

Config:
- Laravel: 5.4
- PHPUnit: 5.7
- PHP: 7.1
- codedungeon/phpunit-result-printer: 0.16.1

Can anyone can help with this?

**Comment by mikeerickson** [comment]
You can surely use PHPUnit 7.0, it just requires version 0.18.2 (which is documented)  having said that, I have intentions to make this clearer in the documentation.
