### ISSUE TITLE
Misaligned status marks

### ISSUE THREAD

**Issue by Braunson** [mikeerickson/phpunit-pretty-result-printer#86]
When running a test with both passing and failing tests the marks are mis-aligned. See my example 

![](https://goo.gl/TSL6Y4)

**Comment by mikeerickson** [comment]
Oh wow, that is strange 

- what version of library are you using 
- what OS 
- what terminal?

**Comment by Braunson** [comment]
@mikeerickson 

Laravel: 5.5 
Package: `^0.16.1` (latest)
OS: Windows 10
Terminal: SmarTTY v2.2

**Comment by mikeerickson** [comment]
OK, I am going to setup a VM to match what you are using and debug this. My apologies for the issue

**Comment by Braunson** [comment]
No need to apologise :), thanks for looking into this!

**Comment by jwhulette** [comment]
![1__default__bash_](https://user-images.githubusercontent.com/4930051/40119467-ca8e2482-58ea-11e8-9683-36ea021e5c7c.png)
I have sort of the same issue.

Laravel: 5.5
PHPUnit: ^7
OS: Mac OS 10.13.4
Issue occurs in: Iterm2, VSCode Terminal

**Comment by mikeerickson** [comment]
Thank you for the report, I will see what I can reproduce along these parameters.

**Comment by mikeerickson** [comment]
@jwhulette would you mind testing this with the `0.19.13` release (just tagged)

**Comment by jwhulette** [comment]
@mikeerickson That looks like it fixed it. Thanks so much!!

**Comment by mikeerickson** [comment]
@jwhulette thank you very much for confirming!
