### ISSUE TITLE
Check mark outlining bug

### ISSUE THREAD

**Issue by roelofjan-elsinga** [mikeerickson/phpunit-pretty-result-printer#88]
![print bug](https://user-images.githubusercontent.com/9220754/39582771-f54a5c50-4eee-11e8-838a-43a9bd8f4de4.png)
Hi, I get this outlining. I didn't change any of the default configuration. This is a docker container, running Ubuntu 16.04. I didn't see anything similar in the other issues, so I thought I'd bring this to your attention. If it's a duplicate, you can just remove this.

**Comment by mikeerickson** [comment]
@roelofjan-elsinga Of course when I attempt to reproduce the issue, all works fine on my end :-( I will continue debugging and try to reproduce.

**Comment by mikeerickson** [comment]
How are you running these tests?  Are you `exec` into the container, or using something like vessel?

**Comment by mikeerickson** [comment]
I remember in the past when I was working on some test work for my employer with old tests, there was some code within the test to force line feed after each test (it was actually buried in the TestCase).  Any chance there is something like this in your code.

When testing without result printer, does it show normal dots across the screen, or does it also add the line feed?

**Comment by mikeerickson** [comment]
Are you using Laravel (cant tell for sure based on directory structure) but I am guessing yes.

**Comment by roelofjan-elsinga** [comment]
I am using Laravel indeed. The tests are run by logging in into the container through docker exec -it container_name bash. I'll get back to you on the default printer. I think I'll also look into TestCase, because I think you may have something there!

**Comment by roelofjan-elsinga** [comment]
I've looked into the default printing, this also has the newline bug. So I'm assuming it also has to do with the TestCase class in my case. Since this has nothing to do with your printer, I'll close my issue.

**Comment by roelofjan-elsinga** [comment]
Just in case anyone else gets this behaviour:

You probably have a space or enter after ?> or before <?php. Yes, it's really that simple.

**Comment by mikeerickson** [comment]
Glad you tracked it down, I had a strong feeling it was something like this (it only because I have experienced it myself as noted)
